### ISSUE TITLE
Фильтрация пар

### ISSUE THREAD

**Issue by vladovello** [HappyPiece/OutOfTimePrototype#4]
**Описание бага:**
Во фрагменте ниже будут выбраны первые 42 записи в БД, и эти записи не обязятально будут соответствовать ограничениям по времени в запросе. Поэтому после проверок на `startDate` и `endDate`, в результате у нас может ни оказаться ни одной пары, не смотря на то, что эти пары существуют в БД.
https://github.com/HappyPiece/OutOfTimeProtorype/blob/83fe5df6ca9831bce486c98e46d1a3a2b8cc3127/OutOfTimePrototype/Services/General/Implementations/ClassService.cs#L27-L46

**Comment by HappyPiece** [comment]
Да, необходимо брать 42 уже после фильтрации. Поправлю в скором времени
